import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"; // Importamos Link aquí
import Header from "@/components/layout/header"; // Tu Header



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="antialiased">
        
        {/* TODO ESTO SE QUEDA FIJO */}
        <nav className="navbar">
          <Header />
          <div className="nav-links">
            <Link href="/">Inicio</Link>
            <Link href="/elementos">Elementos</Link>
            <Link href="/vuelos">Vuelos</Link>
          </div>
        </nav>

        {/* AQUÍ SE RENDERIZA EL CONTENIDO DE CADA PÁGINA */}
        <main>
          {children}
        </main>

      </body>
    </html>
  );
}
